---
roles:
  - name: geerlingguy.java
    version: 1.9.6  # Specify the version needed
  - name: geerlingguy.tomcat
    version: 2.1.0  # Specify the version needed

collections:
  - name: community.docker
    version: 1.3.2  # Specify the version needed
